import mysql.connector
from mysql.connector import errorcode

config = {
    "user": "pysports_user",
    "password": "password",
    "host": "127.0.0.1",
    "database": "pysports",
    "raise_on_warnings": True
}

